# Generated by Django 5.1.3 on 2024-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("archivo", models.ImageField(upload_to="imagenes/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
